{"name": "Test Case 2: Login with valid credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to be visible\nActual value: <element(s) not found> \nCall log:\n  - Expect \"to_be_visible\" with timeout 5000ms\n  - waiting for locator(\"//a[contains(text(),'Logged in as correct')]\")", "trace": "browser = <Page url='https://automationexercise.com/login'>\n\n    @allure.title(\"Test Case 2: Login with valid credentials\")\n    def test_login_valid(browser):\n        home = HomePage(browser)\n        login = LoginPage(browser)\n    \n        home.go_to()\n        home.verify_home_visible()\n        home.click_signup_login()\n        login.verify_login_visible()\n    \n        login.enter_credentials(\"correct@email.com\", \"password123\")\n        login.click_login()\n>       login.verify_logged_in(\"correct\")\n\ntests\\test_auth.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.login_page.LoginPage object at 0x000001EAEEF392B0>, username = 'correct'\n\n    @allure.step(\"Перевірити, що користувач увійшов\")\n    def verify_logged_in(self, username):\n>       expect(self.page.locator(f\"//a[contains(text(),'Logged in as {username}')]\")).to_be_visible()\nE       AssertionError: Locator expected to be visible\nE       Actual value: <element(s) not found> \nE       Call log:\nE         - Expect \"to_be_visible\" with timeout 5000ms\nE         - waiting for locator(\"//a[contains(text(),'Logged in as correct')]\")\n\npages\\login_page.py:23: AssertionError"}, "steps": [{"name": "Перейти на головну сторінку", "status": "passed", "start": 1752404424931, "stop": 1752404428377}, {"name": "Перевірити, що головна сторінка завантажена", "status": "passed", "start": 1752404428377, "stop": 1752404428652}, {"name": "Натиснути 'Signup / Login'", "status": "passed", "start": 1752404428653, "stop": 1752404429224}, {"name": "Перевірити, що форма логіну відображена", "status": "passed", "start": 1752404429225, "stop": 1752404429363}, {"name": "Ввести email та пароль: 'correct@email.com' / 'password123'", "status": "passed", "parameters": [{"name": "email", "value": "'correct@email.com'"}, {"name": "password", "value": "'password123'"}], "start": 1752404429363, "stop": 1752404429428}, {"name": "Натиснути кнопку 'Login'", "status": "passed", "start": 1752404429428, "stop": 1752404429842}, {"name": "Перевірити, що користувач увійшов", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to be visible\nActual value: <element(s) not found> \nCall log:\n  - Expect \"to_be_visible\" with timeout 5000ms\n  - waiting for locator(\"//a[contains(text(),'Logged in as correct')]\")\n\n", "trace": "  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"F:\\QA_Engineer\\TS_Intership\\Playwright_pytest\\pages\\login_page.py\", line 23, in verify_logged_in\n    expect(self.page.locator(f\"//a[contains(text(),'Logged in as {username}')]\")).to_be_visible()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 20382, in to_be_visible\n    self._sync(self._impl_obj.to_be_visible(visible=visible, timeout=timeout))\n    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ~~~~~~~~~~~^^\n  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 741, in to_be_visible\n    await self._expect_impl(\n    ...<5 lines>...\n    )\n  File \"C:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 75, in _expect_impl\n    raise AssertionError(\n        f\"{out_message}\\nActual value: {actual} {format_call_log(result.get('log'))}\"\n    )\n"}, "parameters": [{"name": "username", "value": "'correct'"}], "start": 1752404429842, "stop": 1752404434891}], "start": 1752404424931, "stop": 1752404434898, "uuid": "0f90e87b-5502-4a92-bd7c-536119d2cfc6", "historyId": "5024ab45edc8d37f17388bbaa4378baf", "testCaseId": "5024ab45edc8d37f17388bbaa4378baf", "fullName": "tests.test_auth#test_login_valid", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "DESKTOP-BTCJ9P6"}, {"name": "thread", "value": "16584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}